#!/bin/sh
LIBS="Libraries/External"

if [ "$1" != "" ]; then
    echo "Compiling $1"
    echo ""
    Run/YAAC-ll $1 > a.ll || exit 1
    cat --number a.ll
    llc-6.0 a.ll -o a.s || exit 1
    clang a.s $LIBS/lib.a -o a.out -nopie
    rm a.ll a.s
    echo ""
    echo "Compiled Successfully!"
fi
