#!/bin/sh
LIBS="Libraries/Source"

if [ "$1" != "" ]; then
    echo "Compiling $1"
    echo ""
    Run/YAAC-ll $1 $2 > a.ll || exit 1
    cat --number a.ll
    llc-6.0 a.ll -relocation-model=pic -o a.s || exit 1
    clang a.s $LIBS/lib.so -o a.out || exit 1
    rm a.ll a.s
    echo ""
    echo "Compiled Successfully!"
fi
